# Generated by Django 3.1.2 on 2020-11-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liking',
            field=models.ManyToManyField(related_name='likers', to='network.Post'),
        ),
    ]
